from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth','0012_alter_user_first_name_max_length')]
    operations = [
        migrations.CreateModel(name='ContactMessage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100)),('email',models.EmailField(max_length=254)),('subject',models.CharField(blank=True,max_length=200)),('message',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('phone',models.CharField(blank=True,max_length=20)),('role',models.CharField(choices=[('user','User'),('admin','Admin')],default='user',max_length=10)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to='auth.user'))]),
        migrations.CreateModel(name='Station',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100)),('province',models.CharField(max_length=100))]),
        migrations.CreateModel(name='Train',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('train_number',models.CharField(max_length=50)),('type',models.CharField(max_length=50))]),
        migrations.CreateModel(name='TrainClass',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=50)),('price',models.DecimalField(decimal_places=2,max_digits=10))]),
        migrations.CreateModel(name='Schedule',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('travel_date',models.DateField()),('departure_time',models.TimeField()),('arrival_time',models.TimeField()),('destination',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='arrivals',to='train_ticket.station')),('origin',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='departures',to='train_ticket.station')),('train',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='train_ticket.train'))]),
        migrations.CreateModel(name='Seat',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('number',models.CharField(max_length=5)),('is_booked',models.BooleanField(default=False)),('booked_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='booked_seats',to='auth.user')),('schedule',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='seats',to='train_ticket.schedule'))]),
        migrations.CreateModel(name='Visitor',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('ip_address',models.GenericIPAddressField(blank=True,null=True)),('visit_time',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='Booking',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('price',models.DecimalField(decimal_places=2,max_digits=10)),('booking_date',models.DateTimeField(auto_now_add=True)),('status',models.CharField(choices=[('Pending','Pending'),('Confirmed','Confirmed'),('Cancelled','Cancelled')],default='Pending',max_length=20)),('schedule',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='bookings',to='train_ticket.schedule')),('seat',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='bookings',to='train_ticket.seat')),('ticket_class',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='train_ticket.trainclass')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='bookings',to='auth.user'))]),
        migrations.AddConstraint(model_name='seat',constraint=models.UniqueConstraint(fields=('schedule','number'),name='unique_schedule_seat')),
    ]
